export type Language = 'fr' | 'en';

export const copy = {
  fr: {
    openingTop: 'ET SI NOTRE ÉPOQUE',
    openingMain: "N'ÉTAIT PAS UN CHAOS…",
    openingAnswer: 'MAIS UN SEUIL ?',
    mapTitle: 'UNE CARTE POUR TRAVERSER LE TEMPS',
    mapBody: 'Une lecture méditerranéenne des cycles, des chronologies et de leurs divergences.',
    timelineTitle: 'TROIS CHRONOLOGIES. TROIS VISIONS DU PRÉSENT.',
    tracks: [
      ['SYSTÈME PURANIQUE', '+ 400 000 ANS'],
      ['SRI YUKTESWAR', '4099'],
      ['ENSEIGNEMENT CONTEMPORAIN', '2044 — 2082'],
    ],
    gateTitle: '2044 — 2082',
    gateSub: 'UNE FENÊTRE DE TRANSITION',
    methodTitle: 'NI PROPHÉTIE. NI DÉMOLITION.',
    methodSub: 'UNE CARTE QUI DIT OÙ ELLE SE TROMPE.',
    methodLabels: ['FAIT VÉRIFIÉ', 'TRADITION', 'INTERPRÉTATION', 'CONJECTURE'],
    bookKicker: 'UN ESSAI COURT. UNE ARCHITECTURE LISIBLE.',
    bookTitle: 'LA GRANDE TRANSITION',
    bookSub: '2044–2082 · Une carte lucide du cycle des Yugas',
    cta: 'DÉCOUVREZ LA CARTE COMPLÈTE',
    by: 'THE LUCID CARTOGRAPHER',
  },
  en: {
    openingTop: 'WHAT IF OUR ERA',
    openingMain: 'WERE NOT CHAOS…',
    openingAnswer: 'BUT A THRESHOLD?',
    mapTitle: 'A MAP FOR CROSSING TIME',
    mapBody: 'A Mediterranean reading of cycles, chronologies, and their divergences.',
    timelineTitle: 'THREE CHRONOLOGIES. THREE VISIONS OF THE PRESENT.',
    tracks: [
      ['PURANIC SYSTEM', '+ 400,000 YEARS'],
      ['SRI YUKTESWAR', '4099'],
      ['CONTEMPORARY TEACHING', '2044 — 2082'],
    ],
    gateTitle: '2044 — 2082',
    gateSub: 'A WINDOW OF TRANSITION',
    methodTitle: 'NEITHER PROPHECY NOR DEMOLITION.',
    methodSub: 'A MAP THAT ADMITS WHERE IT MAY BE WRONG.',
    methodLabels: ['VERIFIED FACT', 'TRADITION', 'INTERPRETATION', 'CONJECTURE'],
    bookKicker: 'A SHORT ESSAY. A LEGIBLE ARCHITECTURE.',
    bookTitle: 'THE GREAT TRANSITION',
    bookSub: '2044–2082 · A Lucid Map of the Yuga Cycle',
    cta: 'DISCOVER THE COMPLETE MAP',
    by: 'THE LUCID CARTOGRAPHER',
  },
} as const;
